
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 08 07:48:03 WIB 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 11;
  public static final int LBRACKET = 28;
  public static final int PUT = 33;
  public static final int STRCONST = 45;
  public static final int NUMCONST = 44;
  public static final int ENDSTMT = 22;
  public static final int LPAREN = 9;
  public static final int REPEAT = 35;
  public static final int INT = 43;
  public static final int RPAREN = 16;
  public static final int NOT = 14;
  public static final int AND = 3;
  public static final int LT = 10;
  public static final int OR = 15;
  public static final int BOOL = 42;
  public static final int GET = 26;
  public static final int DIV = 5;
  public static final int UNTIL = 39;
  public static final int LOOP = 30;
  public static final int EXIT = 23;
  public static final int IF = 27;
  public static final int EOF = 0;
  public static final int STRUNCLD = 47;
  public static final int RBRACKET = 34;
  public static final int TRUE = 38;
  public static final int error = 1;
  public static final int MUL = 12;
  public static final int ADD = 2;
  public static final int IDENT = 46;
  public static final int EQ = 6;
  public static final int GTE = 8;
  public static final int LISTSEP = 29;
  public static final int ASSGN = 4;
  public static final int ELSE = 20;
  public static final int SKIP = 36;
  public static final int FUNC = 25;
  public static final int RANGESEP = 40;
  public static final int THEN = 37;
  public static final int NE = 13;
  public static final int OPEN = 31;
  public static final int END = 21;
  public static final int PROC = 32;
  public static final int DEC = 48;
  public static final int CLOSE = 19;
  public static final int FALSE = 24;
  public static final int AS = 18;
  public static final int GT = 7;
  public static final int SUB = 17;
  public static final int VAR = 41;
}

