#!/bin/bash
tname="test$1"
tdir="testcases"
cmd="java parser < $tdir/$tname.txt > $tdir/$tname.out
echo $tdir/$tname.out"
eval $cmd
echo "===== Compile result ====="
cat $tdir/$tname.out
echo ""
echo "===== Run result ====="
cmd="java Machine $tdir/$tname.out > $tdir/$tname.result"
eval $cmd
cat $tdir/$tname.result 